name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Lint the extension
        run: |
          set -eux
          uv run jlpm
          uv run jlpm run lint:check

      - name: Build the extension
        run: |
          set -eux
          uv pip install .

          uv run jupyter labextension list
          uv run jupyter labextension list 2>&1 | grep -ie "@p5-notebook/lab-extension.*OK"
          uv run jupyter labextension list 2>&1 | grep -ie "@p5-notebook/p5-theme-light.*OK"
          uv run jupyter labextension list 2>&1 | grep -ie "@p5-notebook/p5-theme-dark.*OK"
          # uv run python -m jupyterlab.browser_check

      - name: Package the extension
        run: |
          set -eux

          uv pip install build
          uv build

      - name: Upload extension packages
        uses: actions/upload-artifact@v4.6.2
        with:
          name: extension-artifacts
          path: dist/p5_notebook*
          if-no-files-found: error

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - uses: actions/download-artifact@v4.3.0
        with:
          name: extension-artifacts
      - name: Install and Test
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)

          uv sync
          uv pip install "jupyterlab>=4.5.0,<4.6" p5_notebook*.whl


          uv jupyter labextension list
          uv jupyter labextension list 2>&1 | grep -ie "@p5-notebook/lab-extension.*OK"
          uv jupyter labextension list 2>&1 | grep -ie "@p5-notebook/p5-theme-light.*OK"
          uv jupyter labextension list 2>&1 | grep -ie "@p5-notebook/p5-theme-dark.*OK"
          # uv python -m jupyterlab.browser_check --no-browser-test
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
